---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-pvtendpoint
#  claimRef:
#    name: [PVC_NAME]
#    namespace: [PVC_NAMESPACE]
  csi:
    driver: file.csi.azure.com
    volumeHandle: "azurefiles-storage-rg#azurefilessaafc2#myfileshare"	# UPDATE
    volumeAttributes:
      resourceGroup: "azurefiles-storage-rg"				# UPDATE
      storageAccount: "azurefilessaafc2"				# UPDATE
      shareName: "myfileshare"						# UPDATE
      protocol: smb
      server: "azurefilessaafc2.privatelink.file.core.windows.net"	# UPDATE
      networkEndpointType: privateEndpoint
#      clientID: "27704c63-ee0a-4625-a8c7-8c02b314a24c"			# UPDATE IF APPLICABLE - REQ FOR WI
