---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-pvtendpoint
  csi:
    driver: file.csi.azure.com
    volumeHandle: "azurefiles-storage-rg#azurefilessa28f4#myfileshare"	# UPDATE
    volumeAttributes:
      resourceGroup: "azurefiles-storage-rg"				# UPDATE
      storageAccount: "azurefilessa28f4"				# UPDATE
      shareName: "myfileshare"						# UPDATE
      protocol: smb
      server: "azurefilessa28f4.privatelink.file.core.windows.net"	# UPDATE
      networkEndpointType: privateEndpoint
      clientID: "a978cdb2-71b5-41d9-8f7d-8618b8b93c44"			# UPDATE IF APPLICABLE - REQ FOR WI
