---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-pvtendpoint
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
- dir_mode=0640
- file_mode=0640
- uid=0
- gid=0
- mfsymlinks
- cache=strict	# https://linux.die.net/man/8/mount.cifs
- nosharesock
parameters:
  networkEndpointType: privateEndpoint
  protocol: smb
  skuName: Premium_LRS
  storeAccountKey: "false"
