---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 101Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-pvtendpoint
  csi:
    driver: file.csi.azure.com
    volumeHandle: "azurefiles-storage-rg#azurefilessab775#myfileshare"	# UPDATE THIS
    volumeAttributes:
      resourceGroup: "azurefiles-storage-rg"
      storageAccount: "azurefilessab775"	# UPDATE THIS
      shareName: "myfileshare"
      protocol: smb
      server: "azurefilessab775.privatelink.file.core.windows.net"	# UPDATE THIS
      networkEndpointType: privateEndpoint
      #clientID: "3af98405-266e-44f7-8ed5-7dd4057d00c5"	# UPDATE THIS IF APPLICABLE - NEW REQ FOR WI
