---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-pvtendpoint
#  claimRef:
#    name: [PVC_NAME]
#    namespace: [PVC_NAMESPACE]
  csi:
    driver: file.csi.azure.com
    volumeHandle: "azurefiles-storage-rg#azurefilessab83a#myfileshare"	# UPDATE
    volumeAttributes:
      resourceGroup: "azurefiles-storage-rg"				# UPDATE
      storageAccount: "azurefilessab83a"				# UPDATE
      shareName: "myfileshare"						# UPDATE
      protocol: smb
      server: "azurefilessab83a.privatelink.file.core.windows.net"	# UPDATE
      networkEndpointType: privateEndpoint
#      clientID: "37418b09-436a-4922-861b-4c0b6ac13efb"			# UPDATE IF APPLICABLE - REQ FOR WI
