---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 101Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-pvtendpoint
  csi:
    driver: file.csi.azure.com
    volumeHandle: "azurefiles-storage-rg#azurefilessac84a#myfileshare"	# UPDATE THIS
    volumeAttributes:
      resourceGroup: "azurefiles-storage-rg"
      storageAccount: "azurefilessac84a"	# UPDATE THIS
      shareName: "myfileshare"
      protocol: smb
      server: "azurefilessac84a.privatelink.file.core.windows.net"	# UPDATE THIS
      networkEndpointType: privateEndpoint
