---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # "Delete" won't work for statically provisioned fileshare
  storageClassName: azurefile-pvtendpoint
#  claimRef:
#    name: [PVC_NAME]
#    namespace: [PVC_NAMESPACE]
  csi:
    driver: file.csi.azure.com
    volumeHandle: "[STORACCT_NAME]#[FILESHARE_NAME]#[PVC_NAMESPACE]"
    volumeAttributes:
      resourceGroup: "[STORACCT_RG_NAME]"
      storageAccount: "[STORACCT_NAME]"
      shareName: "[FILESHARE_NAME]"
      protocol: smb
      server: "[STORACCT_NAME].privatelink.file.core.windows.net"
      networkEndpointType: privateEndpoint
#      clientID: "[WORKLOAD_IDENTITY_USER_CLIENTID]"			# UPDATE IF APPLICABLE
  mountOptions:
  - dir_mode=0750
  - file_mode=0640
  - uid=0 # change this to your app user's uid
  - gid=0 # leave this, otherwise it can't mount volume
