---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: nginx-wi-ksa	# UPDATE THIS
 namespace: default	# UPDATE THIS
 annotations:
   azure.workload.identity/client-id: “3af98405-266e-44f7-8ed5-7dd4057d00c5”	# UPDATE THIS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-wi
  labels:
    app: nginx-wi
    azure.workload.identity/use: "true"
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx-wi
      azure.workload.identity/use: "true"
  template:
    metadata:
      labels:
        app: nginx-wi
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: nginx-wi-ksa
      containers:
      - name: mypod
        image: nginx:latest
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            cpu: "250m"
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: myvol
          readOnly: false
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: azurefile
