---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-hardlink-creation"
  annotations:
    description: "Blocks creation of a hard links"
spec:
  kprobes:
  - call: "sys_linkat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    - index: 3
      type: "string"
    - index: 4
      type: "int"
    selectors:
    - matchArgs:
      # because this arg is a "string" and not a "file",
      # you can bypass it using relative paths (i.e. ln ./passwd /tmp/myhardlink)
      - index: 1
        operator: "Prefix"
        values:
        - "/etc"
        - "/usr"
      # Override option only available to kernels compiled with CONFIG_BPF_KPROBE_OVERRIDE
      # check /proc/config.gz (if applicable) to see if it is set
      matchActions:
      - action: Override
        argError: -1
