---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-sys-write"
  annotations:
    description: "Blocks writes to files"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/usr/share/nginx/html/index.html"
      # if there's a match, don't act on it 
      # follow it and only act only if it's a write
      matchActions:
      - action: FollowFD
        argFd: 0
        argName: 1
  - call: "sys_write"
    syscall: true
    args:
    - index: 0
      type: "fd"
    - index: 1
      type: "char_buf"
      sizeArgIndex: 3
    - index: 2
      type: "size_t"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/usr/share/nginx/html/index.html"
      matchActions:
      - action: Override
        argError: -1
  - call: "sys_close"
    syscall: true
    args:
    - index: 0
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/usr/share/nginx/html/index.html"
      matchActions:
      - action: UnfollowFD
        argFd: 0
        argName: 0
